
spring:
  data:
    mongodb:
      uri: mongodb+srv://raj715255:Raosatish12345@cluster0.mu79jw4.mongodb.net/?retryWrites=true&w=majority
      database: journaldb
      auto-index-creation: true


server:
  port: 8081
  servlet:
    context-path: /journal

